---
booktitle: Proceedings of the Fourth UK AI Conference 2026
shortname: UK AI Conf
year: '2026'
volume: '348'
start: &1 2026-09-29
end: 2026-09-30
published: 2026-09-30
conference_number: '4'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ukai2026
month: 0
cycles: false
bibtex_editor: Benford, Alistair and B{\"u}y{\"u}kate{\c{s}}, Baturalp and Cabrera,
  Christian and Kiden, Sarah and Salili-James, Arianna and Zakka, Vincent and Zhou,
  Feng
editor:
- given: Alistair
  family: Benford
- given: Baturalp
  family: Büyükateş
- given: Christian
  family: Cabrera
- given: Sarah
  family: Kiden
- given: Arianna
  family: Salili-James
- given: Vincent
  family: Zakka
- given: Feng
  family: Zhou
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fourth UK AI Conference 2026
    Held in The Hilton Nottingham, Nottingham, United Kingdom on 29-30 September 2026

  Published as Volume 348 by the Proceedings of Machine Learning Research on 30 September 2026.

  Volume Edited by:
    Alistair Benford
    Baturalp Büyükateş
    Christian Cabrera
    Sarah Kiden
    Arianna Salili-James
    Vincent Zakka
    Feng Zhou

  Series Editors:
    Tegan Emerson
    Hoel Kervadec
    Neil D. Lawrence
date_str: 29--30 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v348"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v348
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v348
email: ''
conference:
  name: UK AI Conference
  url: https://uk-ai.org/ukai2026/
  location: The Hilton Nottingham, Nottingham, United Kingdom
  dates:
  - *1
  - 2026-09-30
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: ukai26_clean.bib
# Site settings
# Original source:  ukai26_clean.bib
